import { Product, Category } from '@/types';

export const fallbackCategories: Category[] = [
  {
    _id: 'pastries',
    title: 'Pastries',
    slug: { current: 'pastries' },
    description: 'Fresh, buttery pastries made daily with premium ingredients',
    displayOrder: 1,
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: 'breads',
    title: 'Breads',
    slug: { current: 'breads' },
    description: 'Artisanal breads baked using traditional French techniques',
    displayOrder: 2,
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cakes',
    title: 'Cakes',
    slug: { current: 'cakes' },
    description: 'Elegant cakes perfect for celebrations and special occasions',
    displayOrder: 3,
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: 'macarons',
    title: 'Macarons',
    slug: { current: 'macarons' },
    description: 'Delicate almond cookies with luxurious fillings',
    displayOrder: 4,
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: 'beverages',
    title: 'Beverages',
    slug: { current: 'beverages' },
    description: 'Freshly roasted coffee and specialty beverages',
    displayOrder: 5,
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: 'seasonal',
    title: 'Seasonal',
    slug: { current: 'seasonal' },
    description: 'Limited-time offerings featuring seasonal ingredients',
    displayOrder: 6,
    _updatedAt: new Date().toISOString(),
  },
];

export const fallbackProducts: Product[] = [
  // Pastries
  {
    _id: 'croissant',
    name: 'Classic Croissant',
    slug: { current: 'classic-croissant' },
    price: 3.5,
    description:
      'Buttery, flaky croissant made with French butter and traditional lamination technique',
    available: true,
    featured: true,
    ingredients: ['French butter', 'flour', 'yeast', 'salt'],
    allergens: ['gluten', 'dairy'],
    image: '/images/fallback/croissant.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'pastries',
      title: 'Pastries',
      slug: { current: 'pastries' },
    },
  },
  {
    _id: 'pain-au-chocolat',
    name: 'Pain au Chocolat',
    slug: { current: 'pain-au-chocolat' },
    price: 4.25,
    description: 'Crispy croissant pastry filled with rich dark chocolate batons',
    available: true,
    featured: true,
    ingredients: ['French butter', 'flour', 'dark chocolate', 'yeast'],
    allergens: ['gluten', 'dairy'],
    image: '/images/fallback/pain-au-chocolat.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'pastries',
      title: 'Pastries',
      slug: { current: 'pastries' },
    },
  },
  {
    _id: 'almond-croissant',
    name: 'Almond Croissant',
    slug: { current: 'almond-croissant' },
    price: 4.75,
    description: 'Day-old croissant filled with almond cream and topped with sliced almonds',
    available: true,
    featured: false,
    ingredients: ['croissant', 'almond cream', 'sliced almonds', 'powdered sugar'],
    allergens: ['gluten', 'dairy', 'nuts'],
    image: '/images/fallback/almond-croissant.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'pastries',
      title: 'Pastries',
      slug: { current: 'pastries' },
    },
  },
  {
    _id: 'eclair',
    name: 'Chocolate Eclair',
    slug: { current: 'chocolate-eclair' },
    price: 5.25,
    description: 'Choux pastry filled with vanilla custard and topped with chocolate glaze',
    available: true,
    featured: false,
    ingredients: ['choux pastry', 'vanilla custard', 'chocolate glaze'],
    allergens: ['gluten', 'dairy', 'eggs'],
    image: '/images/fallback/eclair.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'pastries',
      title: 'Pastries',
      slug: { current: 'pastries' },
    },
  },

  // Breads
  {
    _id: 'baguette',
    name: 'Traditional Baguette',
    slug: { current: 'traditional-baguette' },
    price: 3.25,
    description: 'Classic French baguette with crispy crust and soft, airy interior',
    available: true,
    featured: true,
    ingredients: ['flour', 'water', 'yeast', 'salt'],
    allergens: ['gluten'],
    image: '/images/fallback/baguette.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'breads',
      title: 'Breads',
      slug: { current: 'breads' },
    },
  },
  {
    _id: 'sourdough',
    name: 'Sourdough Boule',
    slug: { current: 'sourdough-boule' },
    price: 8.5,
    description: 'Round sourdough bread with tangy flavor and chewy texture',
    available: true,
    featured: true,
    ingredients: ['sourdough starter', 'flour', 'water', 'salt'],
    allergens: ['gluten'],
    image: '/images/fallback/sourdough.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'breads',
      title: 'Breads',
      slug: { current: 'breads' },
    },
  },
  {
    _id: 'brioche',
    name: 'Brioche Loaf',
    slug: { current: 'brioche-loaf' },
    price: 12.0,
    description: 'Rich, buttery bread perfect for French toast or sandwiches',
    available: true,
    featured: false,
    ingredients: ['flour', 'eggs', 'butter', 'milk', 'sugar', 'yeast'],
    allergens: ['gluten', 'dairy', 'eggs'],
    image: '/images/fallback/brioche.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'breads',
      title: 'Breads',
      slug: { current: 'breads' },
    },
  },

  // Cakes
  {
    _id: 'opera-cake',
    name: 'Opera Cake',
    slug: { current: 'opera-cake' },
    price: 45.0,
    description: 'Layered almond sponge cake with chocolate ganache and coffee buttercream',
    available: true,
    featured: true,
    ingredients: ['almond flour', 'chocolate ganache', 'coffee buttercream', 'gold leaf'],
    allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
    image: '/images/fallback/opera-cake.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'cakes',
      title: 'Cakes',
      slug: { current: 'cakes' },
    },
  },
  {
    _id: 'mille-feuille',
    name: 'Mille-feuille',
    slug: { current: 'mille-feuille' },
    price: 6.75,
    description: 'Napoleon cake with layers of puff pastry and vanilla pastry cream',
    available: true,
    featured: false,
    ingredients: ['puff pastry', 'vanilla pastry cream', 'fondant icing'],
    allergens: ['gluten', 'dairy', 'eggs'],
    image: '/images/fallback/mille-feuille.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'cakes',
      title: 'Cakes',
      slug: { current: 'cakes' },
    },
  },

  // Macarons
  {
    _id: 'macaron-vanilla',
    name: 'Vanilla Macaron',
    slug: { current: 'vanilla-macaron' },
    price: 2.5,
    description: 'Classic macaron with vanilla bean buttercream filling',
    available: true,
    featured: false,
    ingredients: ['almond flour', 'powdered sugar', 'egg whites', 'vanilla bean'],
    allergens: ['nuts', 'eggs'],
    image: '/images/fallback/macaron-vanilla.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'macarons',
      title: 'Macarons',
      slug: { current: 'macarons' },
    },
  },
  {
    _id: 'macaron-chocolate',
    name: 'Chocolate Macaron',
    slug: { current: 'chocolate-macaron' },
    price: 2.5,
    description: 'Rich chocolate macaron with dark chocolate ganache',
    available: true,
    featured: true,
    ingredients: ['almond flour', 'cocoa powder', 'dark chocolate ganache'],
    allergens: ['nuts', 'eggs', 'dairy'],
    image: '/images/fallback/macaron-chocolate.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'macarons',
      title: 'Macarons',
      slug: { current: 'macarons' },
    },
  },
  {
    _id: 'macaron-raspberry',
    name: 'Raspberry Macaron',
    slug: { current: 'raspberry-macaron' },
    price: 2.75,
    description: 'Delicate pink macaron with fresh raspberry jam filling',
    available: true,
    featured: false,
    ingredients: ['almond flour', 'raspberry jam', 'pink food coloring'],
    allergens: ['nuts', 'eggs'],
    image: '/images/fallback/macaron-raspberry.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'macarons',
      title: 'Macarons',
      slug: { current: 'macarons' },
    },
  },

  // Beverages
  {
    _id: 'espresso',
    name: 'Espresso',
    slug: { current: 'espresso' },
    price: 2.5,
    description: 'Rich, full-bodied espresso made from freshly roasted beans',
    available: true,
    featured: false,
    ingredients: ['espresso beans'],
    allergens: [],
    image: '/images/fallback/espresso.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'beverages',
      title: 'Beverages',
      slug: { current: 'beverages' },
    },
  },
  {
    _id: 'cafe-au-lait',
    name: 'Café au Lait',
    slug: { current: 'cafe-au-lait' },
    price: 4.25,
    description: 'French-style coffee with steamed milk, served in a bowl',
    available: true,
    featured: true,
    ingredients: ['freshly brewed coffee', 'steamed milk'],
    allergens: ['dairy'],
    image: '/images/fallback/cafe-au-lait.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'beverages',
      title: 'Beverages',
      slug: { current: 'beverages' },
    },
  },
  {
    _id: 'hot-chocolate',
    name: 'Chocolat Chaud',
    slug: { current: 'chocolat-chaud' },
    price: 4.75,
    description: 'Rich hot chocolate made with Belgian chocolate and steamed milk',
    available: true,
    featured: false,
    ingredients: ['Belgian chocolate', 'whole milk', 'whipped cream'],
    allergens: ['dairy'],
    image: '/images/fallback/hot-chocolate.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'beverages',
      title: 'Beverages',
      slug: { current: 'beverages' },
    },
  },

  // Seasonal
  {
    _id: 'galette-des-rois',
    name: 'Galette des Rois',
    slug: { current: 'galette-des-rois' },
    price: 28.0,
    description: 'Traditional Epiphany cake with almond cream and hidden charm (January only)',
    available: true,
    featured: true,
    ingredients: ['puff pastry', 'almond cream', 'egg wash', 'ceramic charm'],
    allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
    image: '/images/fallback/galette-des-rois.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'seasonal',
      title: 'Seasonal',
      slug: { current: 'seasonal' },
    },
  },
  {
    _id: 'buche-de-noel',
    name: 'Bûche de Noël',
    slug: { current: 'buche-de-noel' },
    price: 35.0,
    description: 'Traditional Christmas yule log with chocolate sponge and chestnut cream',
    available: false,
    featured: true,
    ingredients: ['chocolate sponge', 'chestnut cream', 'chocolate bark decoration'],
    allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
    image: '/images/fallback/buche-de-noel.jpg',
    _updatedAt: new Date().toISOString(),
    category: {
      _id: 'seasonal',
      title: 'Seasonal',
      slug: { current: 'seasonal' },
    },
  },
];

export const getFallbackMenuData = () => {
  return {
    products: fallbackProducts,
    categories: fallbackCategories,
  };
};
